name: Update K8s App Deployments
on: 
  workflow_dispatch:

jobs:
  verify_service_account:
    name: Verify K8s Service Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
      - name: Create/Verify `.kube` directory
        run: mkdir -p ~/.kube/
      - name: Create kubectl config
        run: |
          cat << EOF >> ~/.kube/config
          ${{ secrets.KUBECONFIG_SA }}
          EOF
      - name: Echo pods
        run: |
          kubectl get pods
      - name: Echo deployments
        run: |
          kubectl get deployments
      - name: Apply App Changes
        run: |
          kubectl apply -f apps/
      - name: Rollout Apps
        run: |
          kubectl rollout restart deployment -n default py-book
          kubectl rollout restart deployment -n default js-book
      - name: Sleep for 90 seconds
        run: |
          sleep 90
      - name: Echo pods
        run: |
          kubectl get pods
      - name: Echo deployments
        run: |
          kubectl get deployments

